# Generated by Django 3.1.4 on 2021-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stockitem_stockuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
